config/routes.rb
Rails.application.routes.draw do
  resources :standards
  get 'statistic/index'
  
  

  resources :daily_records
  resources :henhouses
  resources :periodes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'periodes#index'
end

app/controllers/henhouses_controller.rb
class HenhousesController < ApplicationController
  before_action :set_henhouse, only: [:show, :edit, :update, :destroy]

  # GET /henhouses
  # GET /henhouses.json
  def index
    @henhouses = Henhouse.all
  end

  # GET /henhouses/1
  # GET /henhouses/1.json
  def show
  end

  # GET /henhouses/new
  def new
    @henhouse = Henhouse.new
  end

  # GET /henhouses/1/edit
  def edit
  end

  # POST /henhouses
  # POST /henhouses.json
  def create
    @henhouse = Henhouse.new(henhouse_params)

    respond_to do |format|
      if @henhouse.save
        format.html { redirect_to @henhouse, notice: 'Henhouse was successfully created.' }
        format.json { render :show, status: :created, location: @henhouse }
      else
        format.html { render :new }
        format.json { render json: @henhouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /henhouses/1
  # PATCH/PUT /henhouses/1.json
  def update
    respond_to do |format|
      if @henhouse.update(henhouse_params)
        format.html { redirect_to @henhouse, notice: 'Henhouse was successfully updated.' }
        format.json { render :show, status: :ok, location: @henhouse }
      else
        format.html { render :edit }
        format.json { render json: @henhouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /henhouses/1
  # DELETE /henhouses/1.json
  def destroy
    @henhouse.destroy
    respond_to do |format|
      format.html { redirect_to henhouses_url, notice: 'Henhouse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_henhouse
      @henhouse = Henhouse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def henhouse_params
      params.require(:henhouse).permit(:no, :name, :description, :capacity)
    end
end

app/helpers/henhouses_helper.rb
module HenhousesHelper
end

app/views/henhouses/_form.html.erb
<%= form_for(henhouse) do |f| %>
  <% if henhouse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(henhouse.errors.count, "error") %> prohibited this henhouse from being saved:</h2>

      <ul>
      <% henhouse.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :no %>
    <%= f.text_field :no %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :capacity %>
    <%= f.number_field :capacity %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/henhouses/edit.html.erb
<h1>Editing Henhouse</h1>

<%= render 'form', henhouse: @henhouse %>

<%= link_to 'Show', @henhouse %> |
<%= link_to 'Back', henhouses_path %>

app/views/henhouses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Henhouses</h1>

<table>
  <thead>
    <tr>
      <th>No</th>
      <th>Name</th>
      <th>Description</th>
      <th>Capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @henhouses.each do |henhouse| %>
      <tr>
        <td><%= henhouse.no %></td>
        <td><%= henhouse.name %></td>
        <td><%= henhouse.description %></td>
        <td><%= henhouse.capacity %></td>
        <td><%= link_to 'Show', henhouse %></td>
        <td><%= link_to 'Edit', edit_henhouse_path(henhouse) %></td>
        <td><%= link_to 'Destroy', henhouse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Henhouse', new_henhouse_path %>

app/views/henhouses/new.html.erb
<h1>New Henhouse</h1>

<%= render 'form', henhouse: @henhouse %>

<%= link_to 'Back', henhouses_path %>

app/views/henhouses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>No:</strong>
  <%= @henhouse.no %>
</p>

<p>
  <strong>Name:</strong>
  <%= @henhouse.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @henhouse.description %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @henhouse.capacity %>
</p>

<%= link_to 'Edit', edit_henhouse_path(@henhouse) %> |
<%= link_to 'Back', henhouses_path %>