config/routes.rb
Rails.application.routes.draw do
  resources :standards
  get 'statistic/index'
  
  

  resources :daily_records
  resources :henhouses
  resources :periodes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'periodes#index'
end

app/models/periode.rb
class Periode < ApplicationRecord
  belongs_to :henhouse
  has_many :daily_records
  accepts_nested_attributes_for  :daily_records, allow_destroy: true
end

app/controllers/periodes_controller.rb
class PeriodesController < ApplicationController
  before_action :set_periode, only: [:show, :edit, :update, :destroy]

  # GET /periodes
  # GET /periodes.json
  def index
    @periodes = Periode.all
  end

  # GET /periodes/1
  # GET /periodes/1.json
  def show
    @daily_records = DailyRecord.all.order(:report_date)
  end

  # GET /periodes/new
  def new
    @periode = Periode.new
  end

  # GET /periodes/1/edit
  def edit

  end

  # POST /periodes
  # POST /periodes.json
  def create
    @periode = Periode.new(periode_params)

    respond_to do |format|
      if @periode.save
        format.html { redirect_to @periode, notice: 'Periode was successfully created.' }
        format.json { render :show, status: :created, location: @periode }
      else
        format.html { render :new }
        format.json { render json: @periode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /periodes/1
  # PATCH/PUT /periodes/1.json
  def update
    respond_to do |format|
      if @periode.update(periode_params)
        format.html { redirect_to @periode, notice: 'Periode was successfully updated.' }
        format.json { render :show, status: :ok, location: @periode }
      else
        format.html { render :edit }
        format.json { render json: @periode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /periodes/1
  # DELETE /periodes/1.json
  def destroy
    @periode.destroy
    respond_to do |format|
      format.html { redirect_to periodes_url, notice: 'Periode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_periode
      @periode = Periode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def periode_params
      params.require(:periode).permit(:no, :code, :status, :description, :start_date, :end_date, :total_do, :henhouse_id, daily_records_attributes: [:id, :report_date, :feed_actual, :average_weight, :mortality, :average_temperature, :average_hummidity, :notes, :stockman, :_destroy])
    end
end

app/helpers/periodes_helper.rb
module PeriodesHelper
end

app/views/periodes/_daily_record_fields.html.erb
	<tr>
		<td><%= f.text_field :report_date, :disabled => true %></td>
		<td><%= f.text_field :age %></td>
		<td><%= f.text_field :feed_actual %></td>
	    <td><%= f.text_field :average_weight %></td>
	    <td><%= f.text_field :mortality %></td>
	    <td><%= f.text_field :average_temperature %></td>
	    <td><%= f.text_field :average_hummidity %></td>
		<td><%= f.text_area :notes %></td>
		<td><%= f.text_field :stockman %> </td>
		<td><%= f.check_box :_destroy %></td>
	</tr>
 

app/views/periodes/_form.html.erb
<%= form_for(periode) do |f| %>
  <% if periode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(periode.errors.count, "error") %> prohibited this periode from being saved:</h2>

      <ul>
      <% periode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <label for="formGroupExampleInput">Example label</label>
    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input">
  </div>

   <div class="form-group">
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>
  
 
  
  <div class="form-group">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>


  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="form-group">
    <%= f.label :start_date %>
    <%= f.date_select :start_date %>
  </div>

  <div class="form-group">
    <%= f.label :end_date %>
    <%= f.date_select :end_date %>
  </div>

  <div class="form-group">
    <%= f.label :total_do %>
    <%= f.number_field :total_do %>
  </div>
  

	
  <div class="field"> 
    <%= f.label :henhouse_id %>
	<%= collection_select(:periode, :henhouse_id, Henhouse.all, :id, :name) %>
  </div>


<h3>Daily Record</h3>
<table>
	<th>Tanggal</th>
	<th>Umur </br> (Hari)</th>
	<th>Pemberian Pakan </br> (Bag)</th>
	<th>Berat Rata-Rata </br> (kg)</th>
	<th>Mati </br> (ekor)</th>
	<th>Temperatur </th>
	<th>Kelembaban</th>
	<th>Catatan</th>
	<th>Pekerja</th>
	<tbody>
<%= f.fields_for :daily_records, f.object.daily_records.order(:report_date) do | record | %>
	<%= render 'daily_record_fields', f: record %>
<% end %>
</tbody>
</table>

<%= link_to_add_fields "add Daily Records", f, :daily_records %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/periodes/edit.html.erb
<h1>Editing Periode</h1>

<%= render 'form', periode: @periode %>

<%= link_to 'Show', @periode %> |
<%= link_to 'Back', periodes_path %>

app/views/periodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Periodes</h1>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Kode</th>
      <th>Deskripsi</th>
	  <th>Status</th>
      <th>Mulai</th>
      <th>Selesai</th>
      <th>Jumlah DO</th>
	  <th>Kandang</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @periodes.each do |periode| %>
      <tr>
        <td><%= periode.code %></td>
        <td><%= periode.description %></td>
		<td><%= periode.status %></td>
        <td><%= periode.start_date %></td>
        <td><%= periode.end_date %></td>
        <td><%= periode.total_do %></td>
		<td><%= periode.henhouse.name unless periode.henhouse.blank? %></td>
		
        <td><%= link_to 'Show', periode %></td>
        <td><%= link_to 'Edit', edit_periode_path(periode) %></td>
        <td><%= link_to 'Destroy', periode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Periode', new_periode_path %>

app/views/periodes/new.html.erb
<h1>New Periode</h1>

<%= render 'form', periode: @periode %>

<%= link_to 'Back', periodes_path %>

app/views/periodes/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Code:</strong>
  <%= @periode.code %>
</p>

<p>
  <strong>Status:</strong>
  <%= @periode.status %>
</p>

<p>
  <strong>Description:</strong>
  <%= @periode.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @periode.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @periode.end_date %>
</p>

<p>
  <strong>Total do:</strong>
  <%= @periode.total_do %>
</p>

<p>
	<strong>Daily Record </strong>
	
	<table class="table table-striped">
		<thead>
		<th>Date</th>
		<th scope="row">Age </br> Day(s)</th>
		<th>Feeding </br>(Bag)</th>
		<th>Average </br> Weight</th>
		<th>Mortality</th>
		<th>Average </br>Temperature</th>
		<th>Average </br>Hummidity</th>
		<th>Notes</th>
		<th>Stockman</th>

	</thead>
	<tbody>
	<% @periode.daily_records.each do |record| %>
	<tr>
		<td><%= record.report_date%></td>	
		<th scope="row"><%= record.calculate_age %></td>
		<td><%= record.feed_actual%></td>
		<td><%= record.average_weight%>	</td>
		<td><%= record.mortality %>	</td>
		<td><%= record.average_temperature %>	</td>
		<td><%= record.average_hummidity %>	</td>
		<td><%= record.notes %>	</td>
		<td><%= record.stockman %>	</td>
	</tr>	
	<% end %>
</tbody>
</table>
</p>

<%= link_to 'Edit', edit_periode_path(@periode) %> |
<%= link_to 'Back', periodes_path %>