config/routes.rb
Rails.application.routes.draw do
  resources :standards
  get 'statistic/index'
  
  

  resources :daily_records
  resources :henhouses
  resources :periodes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'periodes#index'
end

app/models/daily_record.rb
class DailyRecord < ApplicationRecord
  belongs_to :periode
  
  def calculate_age
    #temukan tanggal DO masuk
    #1 Temukan DailyRecord ini berasosiasi dengan Periode Apa.
    @periode = self.periode
    @age_day = (self.report_date - @periode.start_date).to_i + 1
  end
end

app/controllers/daily_records_controller.rb
class DailyRecordsController < ApplicationController
  before_action :set_daily_record, only: [:show, :edit, :update, :destroy]

  # GET /daily_records
  # GET /daily_records.json
  def index
    @daily_records = DailyRecord.all
  end

  # GET /daily_records/1
  # GET /daily_records/1.json
  def show
  end

  # GET /daily_records/new
  def new
    @daily_record = DailyRecord.new
  end

  # GET /daily_records/1/edit
  def edit
  end

  # POST /daily_records
  # POST /daily_records.json
  def create
    @daily_record = DailyRecord.new(daily_record_params)

    respond_to do |format|
      if @daily_record.save
        format.html { redirect_to @daily_record, notice: 'Daily record was successfully created.' }
        format.json { render :show, status: :created, location: @daily_record }
      else
        format.html { render :new }
        format.json { render json: @daily_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daily_records/1
  # PATCH/PUT /daily_records/1.json
  def update
    respond_to do |format|
      if @daily_record.update(daily_record_params)
        format.html { redirect_to @daily_record, notice: 'Daily record was successfully updated.' }
        format.json { render :show, status: :ok, location: @daily_record }
      else
        format.html { render :edit }
        format.json { render json: @daily_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daily_records/1
  # DELETE /daily_records/1.json
  def destroy
    @daily_record.destroy
    respond_to do |format|
      format.html { redirect_to daily_records_url, notice: 'Daily record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_record
      @daily_record = DailyRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daily_record_params
      params.require(:daily_record).permit(:report_date, :age, :remedy, :feed_recieved, :feed_actual, :feed_remains, :average_weight, :mortality, :average_temperature, :average_hummidity, :stockman, :notes, :periode_id)
    end
end

app/helpers/daily_records_helper.rb
module DailyRecordsHelper
end

app/views/daily_records/_form.html.erb
<%= form_for(daily_record) do |f| %>
  <% if daily_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(daily_record.errors.count, "error") %> prohibited this daily_record from being saved:</h2>

      <ul>
      <% daily_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :report_date %>
    <%= f.date_select :report_date %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :remedy %>
    <%= f.text_area :remedy %>
  </div>

  <div class="field">
    <%= f.label :feed_recieved %>
    <%= f.number_field :feed_recieved %>
  </div>

  <div class="field">
    <%= f.label :feed_actual %>
    <%= f.number_field :feed_actual %>
  </div>

  <div class="field">
    <%= f.label :feed_remains %>
    <%= f.number_field :feed_remains %>
  </div>

  <div class="field">
    <%= f.label :average_weight %>
    <%= f.text_field :average_weight %>
  </div>

  <div class="field">
    <%= f.label :mortality %>
    <%= f.number_field :mortality %>
  </div>

  <div class="field">
    <%= f.label :average_temperature %>
    <%= f.text_field :average_temperature %>
  </div>

  <div class="field">
    <%= f.label :average_hummidity %>
    <%= f.text_field :average_hummidity %>
  </div>

  <div class="field">
    <%= f.label :stockman %>
    <%= f.text_field :stockman %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="field">
    <%= f.label :periode_id %>
    <%= f.text_field :periode_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/daily_records/edit.html.erb
<h1>Editing Daily record</h1>

<%= render 'form', daily_record: @daily_record %>

<%= link_to 'Show', @daily_record %> |
<%= link_to 'Back', daily_records_path %>

app/views/daily_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Daily records</h1>



<table>
  <thead>
    <tr>
      <th>record date</th>
      <th>Age</th>
	  <th>Calculate Age</th>
      <th>Remedy</th>
      <th>Feed recieved</th>
      <th>Feed actual</th>
      <th>Feed remains</th>
      <th>Average weight</th>
      <th>Mortality</th>
      <th>Average temperature</th>
      <th>Average hummidity</th>
      <th>Stockman</th>
      <th>Notes</th>
      <th>Periode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @daily_records.each do |daily_record| %>
      <tr>
        <td><%= daily_record.report_date %></td>
        <td><%= daily_record.age %></td>
		<td><%= daily_record.calculate_age %></td>
        <td><%= daily_record.remedy %></td>
        <td><%= daily_record.feed_recieved %></td>
        <td><%= daily_record.feed_actual %></td>
        <td><%= daily_record.feed_remains %></td>
        <td><%= daily_record.average_weight %></td>
        <td><%= daily_record.mortality %></td>
        <td><%= daily_record.average_temperature %></td>
        <td><%= daily_record.average_hummidity %></td>
        <td><%= daily_record.stockman %></td>
        <td><%= daily_record.notes %></td>
        <td><%= daily_record.periode.code %></td>
        <td><%= link_to 'Show', daily_record %></td>
        <td><%= link_to 'Edit', edit_daily_record_path(daily_record) %></td>
        <td><%= link_to 'Destroy', daily_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Daily record', new_daily_record_path %>

app/views/daily_records/new.html.erb
<h1>New Daily record</h1>

<%= render 'form', daily_record: @daily_record %>

<%= link_to 'Back', daily_records_path %>

app/views/daily_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>report date:</strong>
  <%= @daily_record.report_date %>
</p>

<p>
  <strong>Age:</strong>
  <%= @daily_record.age %>
</p>

<p>
  <strong>Remedy:</strong>
  <%= @daily_record.remedy %>
</p>

<p>
  <strong>Feed recieved:</strong>
  <%= @daily_record.feed_recieved %>
</p>

<p>
  <strong>Feed actual:</strong>
  <%= @daily_record.feed_actual %>
</p>

<p>
  <strong>Feed remains:</strong>
  <%= @daily_record.feed_remains %>
</p>

<p>
  <strong>Average weight:</strong>
  <%= @daily_record.average_weight %>
</p>

<p>
  <strong>Mortality:</strong>
  <%= @daily_record.mortality %>
</p>

<p>
  <strong>Average temperature:</strong>
  <%= @daily_record.average_temperature %>
</p>

<p>
  <strong>Average hummidity:</strong>
  <%= @daily_record.average_hummidity %>
</p>

<p>
  <strong>Stockman:</strong>
  <%= @daily_record.stockman %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @daily_record.notes %>
</p>

<p>
  <strong>Periode:</strong>
  <%= @daily_record.periode %>
</p>

<%= link_to 'Edit', edit_daily_record_path(@daily_record) %> |
<%= link_to 'Back', daily_records_path %>