config/routes.rb
Rails.application.routes.draw do
  resources :standards
  get 'statistic/index'
  
  

  resources :daily_records
  resources :henhouses
  resources :periodes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'periodes#index'
end

app/models/standard.rb
class Standard < ApplicationRecord
end

app/controllers/standards_controller.rb
class StandardsController < ApplicationController
  before_action :set_standard, only: [:show, :edit, :update, :destroy]

  # GET /standards
  # GET /standards.json
  def index
    @standards = Standard.all
  end

  # GET /standards/1
  # GET /standards/1.json
  def show
  end

  # GET /standards/new
  def new
    @standard = Standard.new
  end

  # GET /standards/1/edit
  def edit
  end

  # POST /standards
  # POST /standards.json
  def create
    @standard = Standard.new(standard_params)

    respond_to do |format|
      if @standard.save
        format.html { redirect_to @standard, notice: 'Standard was successfully created.' }
        format.json { render :show, status: :created, location: @standard }
      else
        format.html { render :new }
        format.json { render json: @standard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /standards/1
  # PATCH/PUT /standards/1.json
  def update
    respond_to do |format|
      if @standard.update(standard_params)
        format.html { redirect_to @standard, notice: 'Standard was successfully updated.' }
        format.json { render :show, status: :ok, location: @standard }
      else
        format.html { render :edit }
        format.json { render json: @standard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /standards/1
  # DELETE /standards/1.json
  def destroy
    @standard.destroy
    respond_to do |format|
      format.html { redirect_to standards_url, notice: 'Standard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_standard
      @standard = Standard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def standard_params
      params.require(:standard).permit(:age_day, :avg_bw, :percent_mort, :fcr, :std_eef)
    end
end

app/helpers/standards_helper.rb
module StandardsHelper
end

app/views/standards/_form.html.erb
<%= form_for(standard) do |f| %>
  <% if standard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(standard.errors.count, "error") %> prohibited this standard from being saved:</h2>

      <ul>
      <% standard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :age_day %>
    <%= f.number_field :age_day %>
  </div>

  <div class="field">
    <%= f.label :avg_bw %>
    <%= f.text_field :avg_bw %>
  </div>

  <div class="field">
    <%= f.label :percent_mort %>
    <%= f.text_field :percent_mort %>
  </div>

  <div class="field">
    <%= f.label :fcr %>
    <%= f.text_field :fcr %>
  </div>

  <div class="field">
    <%= f.label :std_eef %>
    <%= f.number_field :std_eef %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/standards/edit.html.erb
<h1>Editing Standard</h1>

<%= render 'form', standard: @standard %>

<%= link_to 'Show', @standard %> |
<%= link_to 'Back', standards_path %>

app/views/standards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tabel Standar Acuan</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Umur (Hari)</th>
      <th>Berat Rata - Rata</th>
      <th>Kematian (%)</th>
      <th>FCR</th>
      <th>Std EEF</th>
	  <!--
      <th colspan="3"></th>
	  -->
    </tr>
  </thead>

  <tbody>
    <% @standards.each do |standard| %>
      <tr>
        <th scope="row"><%= standard.age_day %></td>
        <td><%= standard.avg_bw %></td>
        <td><%= standard.percent_mort %></td>
        <td><%= standard.fcr %></td>
        <td><%= standard.std_eef %></td>
		<!--
        <td><%= link_to 'Show', standard %></td>
        <td><%= link_to 'Edit', edit_standard_path(standard) %></td>
        <td><%= link_to 'Destroy', standard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Standard', new_standard_path %>

app/views/standards/new.html.erb
<h1>New Standard</h1>

<%= render 'form', standard: @standard %>

<%= link_to 'Back', standards_path %>

app/views/standards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Age day:</strong>
  <%= @standard.age_day %>
</p>

<p>
  <strong>Avg bw:</strong>
  <%= @standard.avg_bw %>
</p>

<p>
  <strong>Percent mort:</strong>
  <%= @standard.percent_mort %>
</p>

<p>
  <strong>Fcr:</strong>
  <%= @standard.fcr %>
</p>

<p>
  <strong>Std eef:</strong>
  <%= @standard.std_eef %>
</p>

<%= link_to 'Edit', edit_standard_path(@standard) %> |
<%= link_to 'Back', standards_path %>